SideStore/SideStore

README.md

I'm assuming this was originally meant as a comment by whoever wrote the README? I don't see why we're telling users how to make something a hyperlink?

Replace redundant text with link

---

.gitmodules
AltStore.xcodeproj/project.pbxproj
AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

+ Removes submodule for `AltSign`
+ Adds `AltSign` as a Swift package
+ Links `AltStoreCore` with `AltSign`
+ Adds `OpenSSL` as a Swift package
+ Links `AltStore` with `OpenSSL`
+ Removes OpenSSL path from framework search directory in `AltStoreCore`

Convert AltSign and OpenSSL into proper Swift packages

---

.gitignore

InteliJ editors automatically generate a `.idea` folder. This should not be commited.

Add InteliJ to git ignore

---

.github/workflows/build.yml
.gitignore
AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

@JoeMatt notified me that it's annoying to have to re-resolve packages when opening the project for the first time.
I have re-added it to git, as well as added a step to the CI to remove it.

Put back Package.resolved, have CI remove it

---

.github/workflows/build.yml
README.md

It doesn't even build on Xcode 13, there is no point pretending it does.

Bump minimum Xcode version to Xcode 14

---

.github/workflows/build.yml

This fixes actions to use stable 14.0.0 as GitHub wouldn’t allow 14.0-beta no longer.
Signed-off-by: Spidy123222

Change Xcode version to 14.0.0

---

AltStore/Info.plist
AltStore/Settings/SettingsViewController.swift

This changes a few settings descriptions to say sidestore instead of AltStore. This also includes pop up for local lan traffic

Change settings altstore names to SideStore

---

README.md

This changes the names for AltStore and altserver to use sidestore and sideserver.

README: Make app names in compile use Side names

---

AltStore/Operations/FetchTrustedSourcesOperation.swift
trustedapps.json

This adds the Pojavlauncher AltStore source as a trusted source in sidestore. I have tested this to work and if you want to try it out you can use my ipa that uses my forks trusted source.
[SideStore 24.zip](https://github.com/SideStore/SideStore/files/9936073/SideStore.24.zip)

Add pojavlauncher to trusted sources

---

AltStore.xcodeproj/project.pbxproj
AltStore/AppDelegate.swift
AltStore/Consts/Consts+Proxy.swift
AltStore/Consts/Consts.swift
AltStore/LaunchViewController.swift
AltStore/Operations/BackgroundRefreshAppsOperation.swift
AltStore/SceneDelegate.swift

Tries 
`Documents/ALTPairingFile.mobiledevicepairing`
then app bundle resources `ALTPairingFile.mobiledevicepairing`, 
finally Info.plist with non default value.
It also checks that the file isn't empty. Should I test if it's a valid plist?
I used `.mobiledevicepairing` instead of `.plist` since XCode wants to compile plists. You can manually move to the Copy phase, but it's easier just to use the other extensions.
Also added an error label if no file found.
Signed-off-by: Joseph Mattello <mail@joemattiello.com>

[#102][#101] Loading view error handling, Load pairingfile from docs, bundle, plist

---

AltStore.xcodeproj/project.pbxproj
AltStoreCore/Model/Source.swift
Build.xcconfig
app.json

This changes version to be 0.1.0 instead and also adds apps.sidestore.io default source link.

Change version on to reflect being pre-release

---

AltStore.xcconfig
AltStore/Operations/FetchProvisioningProfilesOperation.swift
Build.xcconfig
Shared/Extensions/Bundle+AltStore.swift

This fixes refreshing side store app from making a second app because it using legacy AltStore formatted bundleid so I did a simple fix. Unable to stage sidestore during refresh was also fixed by forcing the org id to be group.com.SideStore.SideStore and making sure xconfig applies .SideStore at the end of bundleid and groupID. I have tested this using https://github.com/SideStore/SideStore/pull/120 and it has worked. If you want to do a similar test I Have an action on my GitHub fork here https://github.com/Spidy123222/SideStore/actions/runs/3492216908

Fix Refreshing sidestore and staging error.

---

AltStore/Settings.bundle/Root.plist
AltStore/Settings/AnisetteManager.swift
AltStoreCore/Extensions/UserDefaults+AltStore.swift

This adds a multiple value specifier for anisette servers of which the following are options
Also adds a "Danger Zone" for enabling the use of a custom server instead of one of the defaults.
When the "Use preferred servers" toggle is off then it will prefer whatever is inputted into the "Anisette URL" box and if the toggle is enabled it will use whatever is selected from the multiple value specifier

Better anisette settings

---

AltStore/LaunchViewController.swift

This PR addresses #147 by fixing the selection of `.mobiledevicepairing` file in the pairing file popup, and also allowing `.xml` files to be selected. This also adds a more meaningful message to the user when pairing file selection is cancelled.

Fix .mobiledevicepairing files

---

trustedapps.json

This adds sidestore community store. This change should work but however the store needs to be worked on still so we should merge at a later date.

Add Community store to Trusted Sources

---

AltStore/Base.lproj/Main.storyboard
AltStore/Resources/Assets.xcassets/Colors/SettingsBackground.colorset/Contents.json
AltStore/Resources/Assets.xcassets/Colors/SettingsHighlighted.colorset/Contents.json
AltStore/Settings/Settings.storyboard
AltStoreCore/Resources/Colors.xcassets/Primary.colorset/Contents.json

Better matches the purple of the new icon
Tint color is #A405FA to be used in official source

Change UI Color

---

AltStore/Info.plist

This is a draft to add jit activator methods for sidestore for external apps.
How it's supposed to work is having 69.69.0.1 which is jitstreamer server to have sidestore act as it which this would bring up instant backwards compatibility while apps intergrate sidekit and it will be the fast path since it's more seamless compared to using url scheme which will open app which is useful to activate if sidestore is not awake. 1234567890 is a fake process ID for examples below.
Jitstreamer url http://69.69.0.1/attach/1234567890
What a url scheme could look like 
sidestore://debugpid?url=1234567890

Add SideKit integration

---

AltStore/LaunchViewController.swift
AltStore/Operations/SendAppOperation.swift
minimuxer/minimuxer.swift

I currently have this set to retry 10 times per function. We could probably move the retry amount to a const, or some form of setting for the user, but I thought 10 was decent as a default for now.

Add various retries throughout the Rust function calls

---

.github/workflows/beta.yml
.github/workflows/build.yml
.github/workflows/nightly.yml
.github/workflows/pr.yml
.github/workflows/stable.yml

Update workflow info/notes: https://github.com/SideStore/SideStore/pull/210#issuecomment-1369432170
~~This PR adds some functionality to the GitHub Actions workflow that will upload the built .ipa to a "nightly" release (you can see what it would look like [here](https://github.com/naturecodevoid/SideStore/releases/tag/nightly)).~~ However, you may be wondering why since it already uploads the .ipa as an artifact. Here are some things we can do with a release that would not be possible (or harder to implement) with artifacts:
- Users do not need a github account to download the .ipa
- A simple cloudflare worker could be created that fetches the nightly release from GitHub and responds with an altstore/sidestore source with the latest nightly build, and also the latest stable release. (I …

Revamp actions to have stable, beta and nightly builds

---

AltStore/Browse/BrowseViewController.swift
AltStoreCore/Model/AltStore.xcdatamodeld/AltStore 11.xcdatamodel/contents
AltStoreCore/Model/DatabaseManager.swift
AltStoreCore/Model/InstalledApp.swift
AltStoreCore/Model/NewsItem.swift
AltStoreCore/Model/Source.swift
AltStoreCore/Model/StoreApp.swift
trustedapps.json

This PR changes the following:
- Adapt SideStore source URL and source ID based on if “beta” or “nightly” is in the current version
- Only hide SideStore in Browse if source ID is the same as the current SideStore source ID
- When getting SideStore app, also check if source IDs match up
- Use StoreApp.name for InstalledApp.name to make (Beta)/(Nightly) suffix show up in My Apps
You can test it by adding https://sidestore-apps.naturecodevoid.dev/nightly or https://sidestore-apps.naturecodevoid.dev/beta as a source. Currently, both point to the latest nightly build. ~~We might want to add something that adds the beta/nightly sources to trusted sources **at runtime**. If we just add it to trustedapps.json, there might be conflicts~~

Release channel support

---

AltStore/Operations/FetchProvisioningProfilesOperation.swift

This error is related to App ID creation failure.
App ID name must be an ascii text. It is not allowed to create an App ID with non-ascii text like Chinese, Japanese. If the name is NOT an ascii text, using bundleID instead.
- Fix 'The name for this app is invalid' error

Fix 'The name for this app is invalid' error

---

AltStore/Operations/BackupAppOperation.swift
AltStore/Operations/DeactivateAppOperation.swift
AltStore/Operations/EnableJITOperation.swift
AltStore/Operations/InstallAppOperation.swift
AltStore/Operations/RefreshAppOperation.swift
AltStore/Operations/SendAppOperation.swift

- Fix minimuxer retries throughout the codebase
- Re-add the UI when SideStore refreshes itself alerting the user we have to close to do so

[Patch] Fix minimuxer retries to be more stable

---

AltStore/Managing Apps/AppManager.swift
AltStore/My Apps/MyAppsViewController.swift
AltStore/Operations/FetchProvisioningProfilesOperation.swift
AltStore/Operations/InstallAppOperation.swift

- Modifying checks done before app installation; we now look at whether the provisioning profile we actually get is a free one, instead of relying on the account type.
- Tested with my personal (expired developer) account, this change allows me to install any number of apps. Previously, I would get app ID limit errors, and a prompt to deactivate apps to stay under the 3 app limit.
- Also tested a free account to confirm that checks are still in place there.
Fixes #410

Use provisioning profile details instead of guessing active app limit

---

AltStore/Operations/AuthenticationOperation.swift
AltStore/Operations/ResignAppOperation.swift

- Get UDID from minimuxer instead of Info.plist
Closes #162

feat: remove reliance on Info.plist for getting udid

---

AltStore/LaunchViewController.swift

- changes the intro pop up to have a button that opens the docs page for getting a pairing file rather than before where it was an unclickable plain text url. The app then closes so that the pop up appears next time they open the app.
https://github.com/user-attachments/assets/ebf7b286-cae1-4acd-8523-f0fa933c1547

Better pairing file info

---

AltStore/Settings/AnisetteServerList.swift

- Keep the user custom anisette server list if it is set.
- Add an Alert for reset "adi.pb" to avoid misoperation
- Make the "Back" & "Refresh Servers" clickable area more wide.

feat: show custom anisette server list if set

---

AltStore/Managing Apps/AppManager.swift
AltStore/Operations/InstallAppOperation.swift

1. After the extensions are updated from resignedApp.appExtensions into in-memory installedApp.appExtensions instance and the DB, the same is not reflected in the disk.
2. This causes refresh() operation which looks for plugins(extensions) on the disk to pickup plugins that were already removed during installation to renew the provisioning profiles for these stale plugins eating up AppID.
1. updated InstalledAppOperation.swift to account for the updates to in-memory installedApp.appExtensions instance by removing/deleting those extensions on the disk.
2. updated AppManager.refresh() to stop refreshing when it detects that appExtensions in memory(or in DB) and disk are mismatching and log OperationError.
1. Since refresh will now renew only installed appExtensions with this change, the …

Fix for Refresh Operation causing renewal/install of provisioning profiles for removed app extensions

---

AltStore/Managing Apps/AppManager.swift
AltStore/My Apps/MyAppsViewController.swift
AltStore/Operations/BackupAppOperation.swift
AltStore/Operations/EnableJITOperation.swift
AltStore/Operations/FetchAppIDsOperation.swift
AltStore/Operations/FetchProvisioningProfilesOperation.swift
AltStore/Operations/InstallAppOperation.swift
AltStore/Operations/OperationError.swift
AltStore/Operations/Patch App/PatchAppOperation.swift
AltStore/Operations/RefreshAppOperation.swift
AltStore/Operations/RemoveAppBackupOperation.swift
AltStore/Operations/RemoveAppOperation.swift
AltStore/Operations/ResignAppOperation.swift
AltStore/Operations/SendAppOperation.swift
AltStore/Operations/VerifyAppOperation.swift

- Added reason for erroring out with OperationError.InvalidParameters to further diagnose the refresh issue.

diagnostics: improved error logging for OperationError.invalidParameters

---

AltServer/ErrorDetailsViewController.swift
AltStore.xcodeproj/project.pbxproj
AltStore/Managing Apps/AppManager.swift
AltStore/Operations/DownloadAppOperation.swift
AltStore/Operations/FetchProvisioningProfilesOperation.swift
AltStore/Operations/OperationError.swift
AltStore/Operations/VerifyAppOperation.swift
AltStore/Settings/Error Log/ErrorLogViewController.swift
AltStore/Settings/PatreonViewController.swift
AltStoreCore/Model/StoreApp.swift
AltStoreCore/Patreon/PatreonAPI.swift
Shared/Extensions/NSError+AltStore.swift

- commit 1713fcc which merges Altstore 1.6.3 had missed/dropped some changes which are non-invasive and restoring them now, should help in resolving future merges without much conflicts.
- ErrorDetailsViewController.swift now is used for "viewMoreDetails" in Error Log to show the Error details in sheet view.
- A new method log(error) was added in AppManager to log error as serialized into DB.
- others are self explanatory and minor...

-[cleanup]: restore changes dropped from altstore-1.6.3 merge by 1713fcc

---

AltStore/Extensions/ProcessInfo+SideStore.swift

- Current check for sparserestore is based on currentBuild > targetBuild
- Issue: targetBuild is 18.1b5, and 18.1b5 is not greater than 18.1b5
- Solution: add an equal sign to the check
Note that this doesn't fix the check for 17.7.1 and later 17.x versions.

Add missing = sign

---

AltStore/Managing Apps/AppManager.swift

- Error when refreshing one of the apps sets the error for group context thereby creating same error signature for all.
- This is misleading since the other apps could have proceeded with refresh but due to this "All or nothing" those refresh requests are also ignored BUT MARKED AS SAME ERROR.
- set error only to current AppOperationContext and not the group.context.
- This will enable other refreshable apps to proceed without being interrupted.
NOTE: Since SideStore intentionally takes install path even for refresh request, the removeAppExtensions operation still requires UI context, this bug will be fixed in next PR.

Partial-Fix for #723: Error on refresh operation must be set on self.context instead of group.context

---

AltStore/Settings/SettingsViewController.swift

It's kind of saying the opposite of what it's meant to say.
- Fix a message that appears in the UI under Settings > Refreshing Apps

Update message about Disable Idle Timeout setting

---

.gitignore
AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Default checkout didn't build for me. 
I had to run a Package update in XCode first, but I didn't see an update to Package.resolved.
I changed the .gitignore and added the missing file.
This should perhaps fix clean clones to build.

Change gitignore, add package.resolve

---

AltStore/Authentication/AuthenticationViewController.swift

- updated Error Toast to use .altPrimary color which is proper since primary and accent color is inverted in settings screen.

Fix: update sign-in screen toast text color to be primary color

---

AltStoreCore/Model/DatabaseManager.swift

…st for replaceAt() cannot be same
- added check to see src and dest are not same, before performing replaceAt
- fixes crash causing NSCocoaErrorDomainCode=512
fixes #316

- Fix: DatabaseManager.migrateDatabaseToAppGroupIfNeeded() src and dest for replaceAt() cannot be same

---

AltStore/Operations/FetchAnisetteDataOperation.swift
AltStore/Settings/AnisetteServerList.swift
AltStoreCore/Extensions/UserDefaults+AltStore.swift

1. capture the decoded server list in UserDefaults.standard.menuAnisetteServersList (new variable)
2. ping current server for reachability (expected response code: 200-299 range)
3. traverse servers list (excluding current since it was already processed) to get next reachable server
4. use and make this server as current by setting UserDefaults.standard.menuAnisetteUrl.
1. Though this provides seamless fallback, the user might be annoyed that the server is switching randomly without external input in settings screen. (Need to think if we could make this switch temporary and restore user's selection after the selected server is reachable again).
=> Basically prevent surprises for (say) users who explicitly need only their servers!!
For this, the user could actually remove all unnecessary …

-[Feature]: client-side: Anisette server fallback impl when current server is unreachable

---

AltStore/Operations/FetchAnisetteDataOperation.swift

- Fixed bug where anisette server search will always start from first entry.
- updated to use user's selection first and then fall back, by moving the user selection to top of the list.

- Fix: Anisette-server-fallback: Try currently selected server first

---

AltStore/Managing Apps/AppManager.swift

- in refresh() operation, when validating the extensions, instances of app and context.app were being accessed in async closures while they were already deallocated.
- Fixed by moving the capture outside of async callback closure.

- Fix: refresh(): app was being accessed after de-alloc causing EXC_BREAKPOINT

---

AltStore/Settings/AnisetteServerList.swift

- Refresh Servers was not updating the anisette servers list on the client side, hence disabled local caching before performing url fetch request.

- Fix: AnisetteServers: refresh server request shouldn't use local cache to get proper updates

---

Dependencies/em_proxy.xcodeproj/project.pbxproj

- counter-part changes to match incoming changes in https://github.com/SideStore/em_proxy/pull/3

Renamed libem_proxy.a to libem_proxy-ios.a for iOS builds and added echo to print the lib path being used in the run script

---

Dependencies/fetch-prebuilt.sh

- when minimuxer repo is cloned locally, these files get deleted by fetch-prebuilt.sh during cleanup of generated files marking changes in git.

[fetch-prebuilt.sh] - retain checked-in files from minimuxer repo

---

AltStoreCore/Model/StoreApp.swift

- Added feature(?) where if downloadURL is not specified in apps:{}, it will take the version specified and go to versions[version]["downloadURL"]
- saw a TODO for check if versions:{} is empty, implemented that

added fix for downloadURL error + todo

---

.github/workflows/reusable-sidestore-build.yml
.github/workflows/sidestore-shared.yml
AltStore.xcodeproj/project.pbxproj
AltStore/App Detail/AppContentViewController.swift
AltStore/Base.lproj/Main.storyboard
AltStore/Components/CollapsingTextView.swift
AltStore/My Apps/MyAppsViewController.swift
AltStore/My Apps/UpdateCollectionViewCell.swift
AltStore/My Apps/UpdateCollectionViewCell.xib
SideStore/Views/UIKit/CollapsingMarkdownView.swift
update_release_notes.py

- Render update versionDesc and product's localizedDesc, versionDesc in store as proper (full) markdown instead of using incomplete AlltributedString which doesn't support extensive markdown features.
**Type**: QoL
- Tested on both simulator and real device.
- Tested and corrected colors for both dark and light modes.
- Tested and fixed layout or text overlap issues.
- etc

Feature: Render in-app update description as (full) markdown
