SideStore/SideStore

- AltStoreCore/Model/StoreApp.swift
Supports different IPA urls by platform type, (tvOS, iOS)
This would be needed by Provenance for tvOS side loading
> Multi-platform app target support (tvOS, watchOS etc)

- README.md
Sorry I forgot about this in my last PR lol
> Replace xcodeworkspace with xcodeproj

- AltPlugin/Info.plist
- AltStore.xcodeproj/project.pbxproj
> Pull from Upstream

- README.md
This is just a test PR. You can merge it if you want, doesn't really matter. I was having trouble creating one, so I wanted to try something simple.
Signed-off-by: JJTech <jjtech@jjtech.dev>
> Make it more consistent

- .github/workflows/build.yml
Fresh PR with CI/CD changes to remove all of the trial and error junk from the git history
> Add CI/CD workflow

- README.md
Signed-off-by: JJTech <jjtech@jjtech.dev>
> Add build badge, fix PR badge style

- .github/workflows/build.yml
This will allow testing with older versions of Xcode. Not sure how uploading artifacts will work...
Signed-off-by: JJTech <jjtech@jjtech.dev>
> Convert to build matrix

- AltStore/Info.plist
- AltStore/Settings/SettingsViewController.swift
Reverts SideStore/SideStore#61
> Revert "Change settings altstore names to SideStore"

- AltStore/Info.plist
- AltStore/Settings/SettingsViewController.swift
Reverts SideStore/SideStore#81
> Revert "Revert "Change settings altstore names to SideStore""

- AltStore/LaunchViewController.swift
- minimuxer/minimuxer.swift
I've changed logic to show an alert error message. [Source](https://stackoverflow.com/questions/11862883/attempt-to-present-uiviewcontroller-on-uiviewcontroller-whose-view-is-not-in-the)
> Show error message when pairing file is missing

- README.md
Signed-off-by: jawshoeadan <62785552+jawshoeadan@users.noreply.github.com>
> Update README to include rust specific build instructions

- trustedapps.json
This changes the order the trusted sources in sidestore are in.
> Reorder trusted sources

- AltStore.xcconfig
- AltStore/Info.plist
- AltStore/Settings/AboutPatreonHeaderView.xib
- AltStore/Settings/PatreonViewController.swift
Rebase of #62. Please check I didn’t incorectly resolve conflicts
> Rebase of #62

- trustedapps.json
This adds pokemmo in the list of trusted sources.
> add pokemmo into trusted sources.

- trustedapps.json
This adds Yattee the app to trusted sources for users.
> Add Yattee to trusted sources

- AltDaemon/XPCConnectionHandler.swift
- AltStore/AppDelegate.swift
- AltStoreCore/Components/Keychain.swift
- AltStoreCore/Model/Source.swift
- AltStoreCore/Model/StoreApp.swift
- AltWidget/ComplicationView.swift
- AltWidget/WidgetView.swift
- Shared/Extensions/ALTApplication+AltStoreApp.swift
- Shared/Extensions/Bundle+AltStore.swift
> Auto fetch bundleid REBASE

- Build.xcconfig
> Bump version to 0.3.0

- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
last menu item in Settings VC will open SideStore settings in Settings.app
> Open Settings.app from SettingsVC

- AltStore/Info.plist
- AltStore/Settings/Error Log/ErrorLogViewController.swift
- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
Did some modifications in Settings page.
The changes are as follows:
- Add 'Reset Pairing File'
- Check and share `minimuxer.log` in Error Log page
- Access SideStore `/Document` directory in File App
- Fix some display errors
> Reset Pairing File and checking minimuxer log in app

- AltStore/Settings.bundle/Root.plist
Add the sidestore anisette server as the default anisette server
> Add sidestore anisette server

- AltStore/LaunchViewController.swift
- Changes link from never gonna give you up to the proper pairing instructions https://wiki.sidestore.io/guides/install#pairing-process
> Replace placeholder video with instructions.

- AltStore/Info.plist
- AltStore/Settings.bundle/Root.plist
- removes jkcoxson anisette servers
> Remove jkcoxson anisette servers.

- AltStore.xcodeproj/project.pbxproj
- AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AltStore/Operations/FetchAnisetteDataOperation.swift
- AltStore/Operations/OperationError.swift
- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
- AltStoreCore/Components/Keychain.swift
- AltStoreCore/Extensions/UserDefaults+AltStore.swift
- anisette V3
this should fix most (hopefully all) anisette issues
> anisette V3

- README.md
How else am I ever gonna get the badge on my profile organically, I never co-author any commits 😅
> Simple example of co-authoring a PR

- AltStore/Info.plist
- AltStore/Settings.bundle/Root.plist
This changes anisette server for sidestore to be v3 anisette for the time being.
> Change default anisette to v3 anisette server

- README.md
- changed link from secret-tunnel to em_proxy
> em_proxy link update

- AltStore/App Detail/AppViewController.swift
- AltStore/Components/CollapsingTextView.swift
- AltStore/Components/PillButton.swift
- AltStore/My Apps/MyAppsViewController.swift
- AltStore/News/NewsViewController.swift
- AltStore/Operations/BackupAppOperation.swift
- Fixes multiple deprecation warnings throughout the codebase
- Fixes UIDocumentPicker not working for some when selecting "Open in SideStore"
- Fixes other various UI element sizing and such
> [Chore] Pull upstream changes from AltStore

- AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Updates Altsign from SideStore Repo to latest commit
> Update Altsign (August 6)

- AltStore/Info.plist
- AltStore/Operations/InstallAppOperation.swift
- AltStore/Operations/OperationError.swift
- Dependencies/fetch-prebuilt.sh
- Use ErrorDescription in staging error error message
> Add more information to staging errors

- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
> bugfix(settings): fix rounding issues on clear cache button

- AltStore/Operations/ClearAppCacheOperation.swift
- AltStore/Operations/OperationError.swift
- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
- Do proper error handling
- Make Clear Cache button not crash SideStore
> Clear Cache: Do proper error handling

- AltStore.xcodeproj/project.pbxproj
- AltStore/App IDs/AppIDsViewController.swift
- AltStore/My Apps/MyAppsViewController.swift
- Use `DateComponentsFormatter` to format expiration dates
> Make App ID and App expiration dates more specific

- AltStore.xcodeproj/project.pbxproj
- AltStore/Managing Apps/AppManager.swift
- AltStore/Operations/ClearAppCacheOperation.swift
- AltStore/Operations/OperationError.swift
- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
- Adds Riley’s clear cache button commits.
> Clear cache button

- AltStore/Managing Apps/AppManager.swift
- AltStore/Operations/InstallAppOperation.swift
- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
- AltStoreCore/Extensions/UserDefaults+AltStore.swift
- Modify `UIApplication.shared.isIdleTimerDisabled` during installs
Closes #534
> feat(Operations): don't idle timeout during installations

- AltStore/Settings/Settings.storyboard
- AltStore/Settings/SettingsViewController.swift
- Adds a description to Disable Idle Timeout
- Changes Add to Siri button text to “Allow Siri To Refresh Apps” to better describe what the button is doing accurately.
> Add description on what disable idle timeout toggle + change add to Siri text for accuracy

- AltStore/Settings.bundle/Root.plist
- Add `ani.wesbryie.com` to Anisette server list.
[Got approval from Stern.](https://discord.com/channels/949183273383395328/949183273827983370/1225863647440535604)
> Add ani.wesbryie.com to Anisette list

- AltStore.xcodeproj/project.pbxproj
- AltStore/Settings.bundle/Root.plist
- Add Stossy11's Anisette server to the anisette server list
> Add Stossy11 Anisette Server

- AltStore/Managing Apps/AppManager.swift
- Rename "AltStore" to "SideStore"
> Change "AltStore Expiring Soon" to "SideStore Expiring Soon"

- AltStore/Settings/AnisetteServerList.swift
- Improved the UI on the Anisette Servers View in the app settings.
- Sorry if I broke anything. It seems to be working for me.
> UI Improvements for the Anisette Servers View.

- AltStore/Settings/SettingsViewController.swift
- Added more feedback options.
> Added more feedback options.

- AltStore.xcodeproj/project.pbxproj
- AltStore/AltStore.entitlements
- AltStore/Authentication/Authentication.storyboard
- AltStore/Operations/AuthenticationOperation.swift
> Makes revoking optional

- AltStore.xcodeproj/project.pbxproj
- AltStore/Managing Apps/AppExtensionView.swift
- AltStore/Managing Apps/AppManager.swift
- AltStore/My Apps/MyAppsViewController.swift
- Selective app extension removal
- Change UI for QOL
code is quite self-explanatory, I think I did the UI well enough.
> Selective app extension removal

- AltStore/Intents/IntentHandler.swift
- AltStore/Operations/InstallAppOperation.swift
- changes are self explanatory
> minor fixes for Remove Refreshed.ipa removal and posting from background thread

- AltStore/Managing Apps/AppManager.swift
1. Background Timer/Shortcut based refresh means NO UI CONTEXT.
2. Since SideStore refresh intentionally takes install path instead of refresh, it has to go through removeAppExtensions.
3. removeAppExtensions will throw "OperationError.InvalidParameters" if presentingViewController is nil which is the case during background install. 
4. Hence the background refresh can never complete for SideStore app.
5. This affects both automatic time based background refresh and shortcut based background refresh.
1. if UI context (presentingViewController) is nil, then we can cleanup excess extensions in the current Cached.app that is being installed based on the current extensions in previously installed app if any.
2. Cases covered:
- Background refresh after previous refresh had removed all …
> Background and shortcut refresh fix - remove only excess extensions from new package during install

- AltStore/Settings/SettingsViewController.swift
- Added back the option for email support.
- Updated Twitter account link.
> Twitter Updates & Email Support

- AltStore/Operations/FetchAnisetteDataOperation.swift
… 
- template code to show popup is added when switching the server.
1. add capability to ask user if they really want to have fallback mechanism (Can be made as a switch and toggle data can be stored in core data, this can be inspected before performing fallback).
2. UI ViewContext needs to be properly passed in based on current screen where the operation is requested, else this is a no-op.
> - [Partial-fix]: Show Toast regarding server switch due to fallback if UI context is available

- Dependencies/fetch-prebuilt.sh
commit is self-explanatory
complementary changes for https://github.com/SideStore/em_proxy/pull/3
> updated fetch-prebuilt.sh to reflect libem_proxy-ios.a renaming

- Dependencies/fetch-prebuilt.sh
> [fetch-prebuilt.sh]: force download when libs are missing locally and skip file is absent

- AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
latest commit was 74c9572a3be4c3faeccc835334b7b9af0a7a8d16
> [dependencies]: updated Package.resolved to use latest commit for altsign package

- AltStore.xcodeproj/project.pbxproj
- AltStore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AltStore/Managing Apps/AppManager.swift
- AltStore/Operations/FetchProvisioningProfilesOperation.swift
> Add entitlements

- AltStore/Operations/FetchProvisioningProfilesOperation.swift
- updating features and appgroups in fetching profiles during install was not invoked due to missing "override" keyword in subclass impl
> [Backup]: Fix: update logic during install missed since override keyword was missing

- AltStoreCore/Model/StoreApp.swift
- trustedapps.json
- Fix Aspect Ratio of images displayed from repos
**BEFORE**  
**AFTER**
> Fix Repository App Previews

- .github/workflows/alpha.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable-build-workflow.yml
- .gitignore
- AltStore.xcodeproj/project.pbxproj
- AltStore.xcodeproj/xcshareddata/xcschemes/DataStructuresTests.xcscheme
- AltStore.xcodeproj/xcshareddata/xcschemes/SideStore.xcscheme
- AltStore/Sources/AddSourceViewController.swift
- AltStore/Sources/Components/AddSourceTextFieldCell.swift
- AltStore/Sources/Sources.storyboard
- Makefile
- SideStore/Tests/DataStructureTests.xctestplan
- SideStore/Tests/SideStoreTests.xctestplan
- SideStore/Tests/UITests/UITests.swift
- SideStore/Tests/UITests/UITestsLaunchTests.swift
- SideStore/Tests/UnitTests/datastructures/DataStructuresTests.swift
- SideStore/Tests/UnitTests/datastructures/LinkedHashMapTests.swift
- SideStore/Tests/UnitTests/datastructures/TreeMapTests.swift
- SideStore/Utils/datastructures/LinkedHashMap.swift
- SideStore/Utils/datastructures/TreeMap.swift
- xcconfigs/UITests.xcconfig
- Refer the attached video for the details on the feature
https://github.com/user-attachments/assets/f7354655-1bec-4eba-a524-dc54db290ec4
> Feature: Bulk sources-add in sources screen with capability to stage them before persisting into database

- AltStoreCore/Model/InstalledApp.swift
- Fix bug in version comparison
> fix: typo in hasUpdate comparison

- README.md
yeah i'm petty >:3
Changed Readme to add StosVPN
- Readme change
> Added StosVPN to the EM Proxy part.
